---
title: "Evening Nebula"
type: "challenge"
description: "Learn JS basics by getting a test suite to pass."
visibility: "assign"
tags: "evening-exercise, javascript, tdd"
ignore:
  - "evening-nebula.md"


